 

import type { Metadata } from 'next'
import { Inter, Open_Sans } from 'next/font/google'
import './globals.scss'
import Header from './components/organisms/Header'  
import LayoutWrapper from './LayoutWrapper'   
import CartContext from './components/organisms/CartContext'
import Providers from './Providers'
import { getServerSession } from 'next-auth'
import { authOptions } from '../../pages/api/auth/[...nextauth]'
import WishListContext from './components/atoms/WishListContext'
import CartModal from './components/organisms/CartModal'
import Footer from './components/organisms/Footer'
export const open_sans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  weight:'variable',
  variable:'--font-open-sans'
})

export const inter = Inter({
  subsets: ['latin'],
  display: 'swap', 
  variable:'--font-inter'

})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session =  await getServerSession(authOptions);

  
  return (  
    <html lang="en" className={`${open_sans.variable}  ${inter.variable} `}> 
      <body>
        <Providers session={session}> 
        <CartContext>
          <WishListContext>
              <div  className="flex flex-col h-screen " >
                <Header/>
                <div className="flex-grow" >
                <LayoutWrapper> 
                  {children} 
                </LayoutWrapper> 
                </div> 
                <Footer/>
              </div>
          </WishListContext> 
        </CartContext> 
        </Providers> 
      </body>
    </html>
  )
}

 